
services:
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000' # Port API
            - '${FORWARD_MINIO_CONSOLE_PORT:-9001}:9001' # Port Console (UI)
        environment:
            MINIO_ROOT_USER: 'sail'
            MINIO_ROOT_PASSWORD: 'password'
        volumes:
            - 'minio_data:/data'
        command: minio server /data --console-address ":9001"
        networks:
            - sail

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            set -e;
            until /usr/bin/mc alias set myminio http://minio:9000 sail password; do
              echo 'MinIO non prêt, nouvelle tentative dans 2s...';
              sleep 2;
            done;
            /usr/bin/mc mb -p myminio/${AWS_BUCKET:-mibeko-documents} || true;
            /usr/bin/mc anonymous set download myminio/${AWS_BUCKET:-mibeko-documents} || true;
            exit 0;
            "
        networks:
            - sail

    postgres:
        #image: 'postgres:16-alpine'
        image: 'pgvector/pgvector:pg16'
        container_name: 'postgres-mibeko'
        ports:
            - '${FORWARD_POSTGRES_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE:-mibeko}'
        volumes:
            - 'postgres_data:/var/lib/postgresql/data'
        networks:
            - sail
    rabbitmq:
        image: 'rabbitmq:4-management'
        container_name: 'rabbitmq-mibeko'
        ports:
            - '${FORWARD_RABBITMQ_PORT:-5672}:5672'
            - '${FORWARD_RABBITMQ_CONSOLE_PORT:-15672}:15672'
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER:-guest}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD:-guest}'
        networks:
            - sail

    dbeaver:
        image: 'dbeaver/cloudbeaver:latest'
        container_name: 'dbeaver-mibeko'
        ports:
            - '${FORWARD_DBEAVER_PORT:-8978}:8978'
        volumes:
            - 'dbeaver_workspace:/opt/cloudbeaver/workspace'
        networks:
            - sail
        depends_on:
            - postgres
volumes:
    minio_data:
        driver: local
    postgres_data:
        driver: local
    rabbitmq_data:
        driver: local
    dbeaver_workspace:
        driver: local
networks:
    sail:
        driver: bridge
