name: Nettoyage des anciennes images Docker

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    # --- AJOUTE CE BLOC ICI ---
    permissions:
      packages: write
      contents: read
    # --------------------------

    steps:
      - name: Supprimer les anciennes versions du package
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'mibeko-dashboard'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
